### ISSUE TITLE
docker: Anrufbeantworter nimmt anrufe manchmal nicht ab

### ISSUE THREAD

**Issue by f321x** [haumacher/phoneblock#147]
Ich betreibe den AB als Docker container im heimnetz mit einer FRITZ!Box 6690 Cable, leider scheint die sip registrierung zwischen AB und FritzBox nicht über die 300sec bestehen zu bleiben. Wenn die sip registrierung neu ist (den logs entnommen) funktioniert alles einwandfrei, aber wenn sie eine zeit lange aktiv ist (z.B. 200 sec) funktionieren die test anrufe (lokale test nummer des AB) nicht mehr (anruf wird nicht abgenommen und bricht ab). Nach erneuerung der sip registrierung funktioniert es wieder eine gewisse zeit. 

Mit den vollen SIP paket logs wird in den fällen in welchen der Anruf fehlschlägt auch kein eingehendes Paket angezeigt, der AB scheint also nicht von der FritzBox kontaktiert zu werden?
Eventuell würde es helfen das Registrierungsintervall von 300 Sekunden zu verkürzen? Gibt es hierzu bereits eine config variable?

Das ist das docker compose setup:
```
  phoneblock:
    image: phoneblock/answerbot:latest  (stand 30.03.25)
    container_name: phoneblock
    network_mode: host
    environment:
      - PHONEBLOCK_API_KEY=APIKEY
      - SIP_USER=phoneblock
      - SIP_PASSWD=PASSWORT
      - VIA_ADDR=auto-configuration
      - VIA_ADDR_V6=auto-configuration
      - HOST_PORT=50060
      - REGISTRAR=fritz.box
      - ROUTE=fritz.box;lr
      - REALM=fritz.box
      - MEDIA=audio 4080 RTP/AVP { 8 PCMA 8000 160 }
      - MIN_SILENCE_TIME=1500
      - PADDING_TIME=500
      - SILENCE_DB=-35
      - MEDIA_PORT=50100
      - LOG_ALL_PACKETS=no
      - PORT_COUNT=10
      - MIN_VOTES=4
      - RECORDINGS=/opt/phoneblock/recordings
      - CONVERSATION=/opt/phoneblock/conversation
    volumes:
      - ./phoneblock/conversation:/opt/phoneblock/conversation
      - ./phoneblock/recordings:/opt/phoneblock/recordings
    restart: always

```
