### ISSUE TITLE
Registrierung fehlgeschlagen: No response. (Fehler 404).

### ISSUE THREAD

**Issue by geimist** [haumacher/phoneblock#98]
Mit dem AB sah ich die Möglichkeit, auch ältere FritzBoxen oder CardDAV-Anbindung für PhoneBlock nutzen zu können. Beim Versuch, den AB auf zwei unterschiedlichen FritzBox 7412 einzurichten, erhalte ich in der WebGUI jedoch sofort den Fehler: `Registrierung fehlgeschlagen: No response. (Fehler 404).`

Die MyFritz-Adresse funktioniert allerdings einwandfrei und auch mit dem PhoneBlock-DDNS ändert sich daran nichts. Liegt es möglicherweise an dem selbst ausgestellten SSL-Zertifikat der alten Boxen? 

![Bildschirmfoto 2024-11-12 um 19 59 33](https://github.com/user-attachments/assets/6686e517-5549-4e4a-9c72-a90629845e86)

**Comment by haumacher** [comment]
Das SSL-Zertifikat der Box spielt keine Rolle, die Kommunikation zwischen AB und Box erfolgt über SIP. Kannst Du mir mal bitte die ersten paar Zeichen der Anrufbeantworter-Kennung mitteilen, dann könnte ich mir das mal von AB-Seite aus anschauen.

**Comment by tomghub** [comment]
Ist die Dyndns Adresse auch IP4 und IP6 zugeordnet? Es gibt da Tools z.b. nslookup.io.
Ist das Telefoniegerät in der FB ins Internet freigegeben?

**Comment by haumacher** [comment]
So kommt das auch bei PhoneBlock an - die IPv4-Adresse ist stabil registriert, Updates funktionieren. Die Box hat offensichtlich einen offenen SIP-Port:

```
nmap -Pn 89.247.xxx
Starting Nmap 7.80 ( https://nmap.org ) at 2024-11-13 14:50 CET
Nmap scan report for i59Fxxx.versanet.de (89.247.xxx)
Host is up (0.46s latency).
Not shown: 999 filtered ports
PORT     STATE SERVICE
5060/tcp open  sip
```

In den Logs steht 

```
[2024-11-13 10:54:27] INFO: [org.mjsip.ua.registration.RegistrationClient]: Registration of <sip:ab-76125728xxx@128.140.84.131> failed: 404 Not Found
```

Auf dem Live-System ist kein Debug-Logging aktiviert, daher kann ich die ausgetauschten Nachrichten nicht sehen. Könntest Du die Box mal auf dem Testsystem anmelden, da kann ich Message-Logging einschalten - vielleicht finden wir heraus, wo's klemmt.

Bitte beachte: Auf dem Testsystem funktioniert der DynDNS-Dienst nicht mehr, da ich auf einer IP keine zwei Nameserver betreiben kann. Daher lass die DynDNS-Registrierung auf dem Live-System und verwende die fb-....box.phoneblock.net Adresse für die Erzeugung des AB auf dem Testsystem. 

Das Testsystem ist gerade etwas "durcheinander", um die Anrufbeantworter-App aufzurufen, nutze bitte die URL hier: https://phoneblock.net/pb-test/ab/  - der Klick auf der Webseite führt gerade in Leere - weiß noch keiner wo das herkommt.

**Comment by geimist** [comment]
Ich hab den AB jetzt auf einer anderen FritzBox 7412 konfiguriert (gleicher Fehler, was zu erwarten war).
Die Kennung lautet: `ab-297921984391xxxx`

**Comment by haumacher** [comment]
Das ist interessant, die Fritz!Box antwortet tatsächlich auf den Registrierungsversuch, aber sie sagt `SIP/2.0 404 Not Found`. Das scheint zu bedeuten, dass sie der Auffassung ist, dass der "Nutzer" "ab-297921..." - also das "Telefoniegerät", das eigentlich in der Fritz!Box eingerichtet sein sollte - nicht existiert/gefunden werden kann. 

```
[2024-11-14 18:18:51] INFO: [de.haumacher.phoneblock.ab.SipService]: No active registration for user 'ab-297921xxx'.
[2024-11-14 18:18:51] INFO: [de.haumacher.phoneblock.ab.SipService]: Resolved IPv4 address for 'ab-297921xxx' (t0mcszxxx.myfritz.net): 46.95.xxx
[2024-11-14 18:18:51] INFO: [de.haumacher.phoneblock.ab.SipService]: Started registration for ab-297921xxx.
[2024-11-14 18:18:51] INFO: [org.mjsip.sip.provider.SipProvider]: Sent message to: 46.95.xxx:5060/udp (426 bytes).
-----Begin-of-message-----
REGISTER sip:fritz.box SIP/2.0
Via: SIP/2.0/UDP 128.140.84.131:50060;branch=z9hG4bKb2baeaa5
Route: <sip:46.95.xxx;lr>
Max-Forwards: 70
To: <sip:ab-297921xxx@fritz.box>
From: <sip:ab-297921xxx@fritz.box>;tag=634631636462
Call-ID: 229552221678@128.140.84.131
CSeq: 1 REGISTER
Contact: <sip:ab-297921xxx@128.140.84.131:50060>
Expires: 3600
User-Agent: mjsip 1.9.0-SNAPSHOT
Content-Length: 0


-----End-of-message-----
[2024-11-14 18:18:51] INFO: [de.haumacher.phoneblock.ab.CreateABServlet]: Answerbot enabled for: bc037aac-cbf0-45e9-8c39-dd07987c72e7
[2024-11-14 18:18:51] INFO: [org.mjsip.sip.provider.SipProvider]: Received message from: 46.95.xxx:5060/udp (306 bytes).
-----Begin-of-message-----
SIP/2.0 404 Not Found
Via: SIP/2.0/UDP 128.140.84.131:50060;branch=z9hG4bKb2baeaa5
From: <sip:ab-297921xxx@fritz.box>;tag=634631636462
To: <sip:ab-297921xxx@fritz.box>;tag=2C762347E7F69519
Call-ID: 229552221678@128.140.84.131
CSeq: 1 REGISTER
User-Agent: FRITZ!OS
Content-Length: 0


-----End-of-message-----
[2024-11-14 18:18:51] INFO: [org.mjsip.ua.registration.RegistrationClient]: Registration of <sip:ab-297921xxx@128.140.84.131:50060> failed: 404 Not Found
[2024-11-14 18:18:51] WARN: [de.haumacher.phoneblock.ab.SipService]: Failed to register ab-297921xxx (1 failures): 404 Not Found
[2024-11-14 18:18:51] WARN: [de.haumacher.phoneblock.ab.SipService]: Stopping temporary registration 'ab-297921xxx'.
```

Wenn man nicht bei AVM anrufen will, dann kann man jetzt nur anfangen zu raten. Vielleicht könnte die alte Box etwas gegen den etwas länglichen Benutzernamen "ab-...." haben. Ich ändere den mal in der DB auf "ab2979". Kannst Du in der FritzBox die Zugangsdaten mal dahingehend ändern und einen neuen Verbindungsversuch machen?

**Comment by geimist** [comment]
Der Benutzername muss mindestens 8 Zeichen lang sein. 🙈
Ich hab jetzt diesen gesetzt `ab297921`.

PS: Du musst dir aber damit auch nicht die Zeit verschwenden. Es ist nicht schlimm, wenn es da nicht klappt. Es sei denn, die reizt die Fehlersuche. Dann können wir das gern ergründen.

**Comment by haumacher** [comment]
Ich würde eigentlich gerne herausfinden, wie es auf einer alten Box geht, es gibt viele Anfragen diesbezüglich.

Ich habe jetzt den Nutzernamen in der DB aktualisiert, bitte versuch nochmal zu verbinden.

**Comment by geimist** [comment]
So sieht ein Verbindungsversuch in den erweiterten Supportdaten der FB aus:
```  
2024-11-15 21:05:00.866 - IN: my=192.168.178.1%8:5060 peer=128.140.84.131 port=50060 UDP, sipiface=none:
REGISTER sip:fritz.box 2.0
Via: SIP/2.0/UDP 128.140.84.131:50060;branch=z9hG4bK96841db5
Route: <sip:46.95.125.85;lr>
From: <sip:ab297921@fritz.box>;tag=691936626953
To: <sip:ab297921@fritz.box>
Call-ID: 567153739879@128.140.84.131
CSeq: 1 REGISTER
Contact: <sip:ab297921@128.140.84.131:50060>
Max-Forwards: 70
Expires: 3600
User-Agent: mjsip 1.9.0-SNAPSHOT
Content-Length: 0



2024-11-15 21:05:00.868 - OUT: my=192.168.178.1%8:5060 peer=128.140.84.131 port=50060 UDP, sipiface=none tcclass=sip, netmark=0:
SIP/2.0 404 Not Found
Via: SIP/2.0/UDP 128.140.84.131:50060;branch=z9hG4bK96841db5
From: <sip:ab297921@fritz.box>;tag=691936626953
To: <sip:ab297921@fritz.box>;tag=A5C7096167974C1E
Call-ID: 567153739879@128.140.84.131
CSeq: 1 REGISTER
User-Agent: FRITZ!OS
Content-Length: 0
```

**Comment by haumacher** [comment]
Interessant. Und das blöde Ding sagt nicht, warum es zu dem Schluss kommt, dass das Gerät nicht existiert... Wie hast Du das Gerät denn in der Box genannt? Kannst Du das  mal auch "ab297921" nennen - wer weiß, vielleicht muss die Kontaktadresse hier der Gerätename und nicht der Login-Name sein... aber das ist schon dünnes Eis...

**Comment by geimist** [comment]
Es hieß `Spam-AB`. Hab es auch mal gleich dem Usernamen umbenannt – leider ohne Erfolg.

**Comment by haumacher** [comment]
Da fällt mir leider auch nichts mehr zu ein. Geht die Registrierung bei der alten Box vom internen Netzwerk aus (mit der Docker-Version)?

**Comment by geimist** [comment]
Bevor ich es via VPN zu einer FritzBox 7412 probiere, wollte ich es zunächst zu einer Box versuchen, die in deren Netz mit Docker funktioniert. Leider klappte bereits das nicht. Die Umgebungsvariablen habe ich von `fritz.box` auch die entfernte IP `192.168.177.1` angepasst. Ist die Anpassung mit einer IP statt `fritz.box` so korrekt?

```YAML
version: '3.9'

services:
  phoneblock:
    image: phoneblock/answerbot:latest
    container_name: phoneblock-vpn-test
    network_mode: host
    environment:
      # description: https://github.com/haumacher/phoneblock/blob/master/phoneblock-ab/.phoneblock.template
      - SIP_USER=phoneblock
      - SIP_PASSWD=xxx
      - PHONEBLOCK_USERNAME=xxx
      - PHONEBLOCK_PASSWORD=xxx
      - VIA_ADDR=auto-configuration
      - VIA_ADDR_V6=auto-configuration
      - HOST_PORT=50060
      - REGISTRAR=192.168.177.1
      - ROUTE=192.168.177.1;lr
      - REALM=192.168.177.1
      - MEDIA=audio 4080 RTP/AVP { 8 PCMA 8000 160 }
      - MIN_SILENCE_TIME=1500
      - PADDING_TIME=500
      - SILENCE_DB=-35
      - MEDIA_PORT=50100
      - PORT_COUNT=10
      - RECORDINGS=none
      - CONVERSATION=/opt/phoneblock/conversation
    volumes:
      - ./conversation:/opt/phoneblock/conversation
    restart: on-failure:5
```

Kann man mehrere ABs parallel betreiben, bzw. wie und welche Ports sind da in den Umgebungsvariablen zu ändern?
